//
// Created by luigi on 11/03/24.
//

#ifndef INGEGNERIA_DEL_SOFTWARE_SETTINGSCONFIGURATION_H
#define INGEGNERIA_DEL_SOFTWARE_SETTINGSCONFIGURATION_H


class SettingsConfiguration {

};


#endif //INGEGNERIA_DEL_SOFTWARE_SETTINGSCONFIGURATION_H
