//
// Created by luigi on 29/02/24.
//

#ifndef INGEGNERIA_DEL_SOFTWARE_PROFILEPANEL_H
#define INGEGNERIA_DEL_SOFTWARE_PROFILEPANEL_H


class ProfilePanel {

};


#endif //INGEGNERIA_DEL_SOFTWARE_PROFILEPANEL_H
